version: 2.1
workflows:
  testing:
    jobs:
      - runner-proxy

jobs:
  runner:
    machine: true
    resource_class: crowley-namespace/runner-kub
    steps:
      - run: echo "Testing Workspace on Runner!" >> /tmp/testing.txt
      - persist_to_workspace:
          root: /tmp
          paths:
            - testing.txt

  ppc64le:
    machine: true
    resource_class: crowley-namespace/ppc64le
    steps:
      - run: echo "Testing PowerPC based Runner!"


  runner-proxy:
    machine: true
    resource_class: crowley-namespace/runner-proxy
    steps:
      - run: echo "Testing Behind a Runner Proxy on amd64!"

  docker_build:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    steps:
      - attach_workspace:
          at: /tmp
      - run: cat /tmp/testing.txt



      