version: 2.1
workflows:
  testing:
    jobs:
      - runner

jobs:
  runner:
    machine: true
    resource_class: crowley-namespace/multi-arch-amd64
    steps:
      - run: echo "Hi I'm on Runners!"
