version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: sleep 60
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: sleep 30
      - run: echo "this is the test job"

  deploy:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: sleep 20
      - run: echo "this is the deploy job"

  runner:
    machine: true
    resource_class: crowley/testing12343234213423142134212134
    steps:
      - run: echo "Hi I'm on Runners!"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
      - rubber:
          requires:
            - test